[package]
name = "semilattice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixedbitset = "0.4.2"
nom = "7.1.3"
pest = "2.7.5"
pest_derive = "2.7.5"
petgraph = "0.6.4"
thiserror = "1.0.50"
